<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Dashboard Tickets Clínica Dávila - Pantalla 1</title>

    <link href="<?php echo BASE_URL."views/dashboard/"; ?>css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo BASE_URL."views/dashboard/"; ?>css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php echo BASE_URL."views/dashboard/"; ?>css/docs.css" rel="stylesheet">
    <script src="<?php echo BASE_URL."views/dashboard/"; ?>js/jquery.js"></script>

    <!-- FlexSlider  -->
    <script src="<?php echo BASE_URL."views/dashboard/"; ?>js/modernizr.js"></script>

    <!-- Script HighCharts -->
    <script type="text/javascript" src="<?php echo BASE_URL."views/dashboard/"; ?>js/jquery.min.js"></script>

    <!-- js de recuperacion de datos -->
	<script type="text/javascript">
		<?php 
		echo $this->cod_mesSemjs;
		?>
	</script>
</head>

<body>


<div class="container">



     <div class="row-fluid">  
        <div class="span12">
            <div class="navbar">
              <div class="navbar-inner">
                <div class="container">                 
                    <a href="#" class="brand">Dashboard Tickets</a>
                    <div class="nav-collapse collapse navbar-responsive-collapse">
                    <ul class="nav pull-right">                     
                        <li class="divider-vertical"></li>
                        <li><a href="#">Comparativo</a></li>
                        <li><a href="#">Hardware</a></li>
                        <li class="active"><a href="#">Software</a></li>
                        <li><a href="<?php echo BASE_URL; ?>dashboard/tabla">Tabla</a></li>
                    </ul>
                    </div><!-- /.nav-collapse -->
                    </div>
              </div><!-- /navbar-inner -->
            </div>

        </div>
    </div>





    <div class="row">
        <div class="span5titulo" style="text-align: left;">
            <div class="navbar">
                <div class="navbar-inner">                   
                    <ul class="nav ">                  
                        <li><a href="#">Software</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="span5space"></div>
        <div class="span1">
                <div class="alert alert-info"><?php echo $this->label_menosde30; ?></div>
        </div>
        <div class="span1">
                <div class="alert alert-success"><?php echo $this->label_menosde60; ?></div>
        </div>
        <div class="span1">
                <div class="alert alert-error"><?php echo $this->label_masde60; ?></div>
        </div>
        <div class="span2space"></div>
        <div class="span2menu">
            <div class="navbar">
                <div class="navbar-inner">                   
                    <ul class="nav ">
                        <li><a href="<?php echo BASE_URL;?>">Dia</a></li>
                        <li class="active"><a href="<?php echo BASE_URL;?>dashboard/semestre">Mes</a></li>
                        <li><a id="mar7" href="<?php echo BASE_URL;?>dashboard/anual">Año</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6"><div id="sw-cr-mes" class="span6g span6gmb"></div></div>
        <div class="span6"><div id="sw-tr-mes" class="span6g span6gmb"></div></div>
    </div>
    <div class="row-fluid">
        <div class="span6"><div id="sw-mt-mes" class="span6g"></div></div>
        <div class="span6"><div id="sw-sc-mes" class="span6g"></div></div>        
    </div>



</div>


<!-- Script HighCharts -->
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/highcharts.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/modules/exporting.js"></script>   


<!-- Script Carrusel Bootstrap -->
<script type="text/javascript" src="<?php echo BASE_URL."views/dashboard/"; ?>js/widgets.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-transition.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-alert.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-modal.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-dropdown.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-scrollspy.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-tab.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-tooltip.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-popover.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-button.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-collapse.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-carousel.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-typeahead.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/bootstrap-affix.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/holder/holder.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/google-code-prettify/prettify.js"></script>
<script src="<?php echo BASE_URL."views/dashboard/"; ?>js/application.js"></script>

</body>

</html>

